title: Gopal Erinjippurath
description: >-
  Scaling AI for capital markets.<br><br>
  Post-exit founder of Sust Global (acquired by ISS STOXX), pre-IPO leader at Planet Labs (NYSE:PL), and private markets investor backing frontier tech.
show_downloads: false
google_analytics: G-RJ80K62TF0
theme: jekyll-theme-minimal
