title: Gopal Erinjippurath
description: Creating AI products. Founded Sust Global (acquired by ISS STOXX). Led analytics and applied AI at Planet Labs.
show_downloads: false
google_analytics: G-RJ80K62TF0
theme: jekyll-theme-minimal
