title: Gopal Erinjippurath
description: Creating Geospatial AI. Founded Sust Global. Led AI and insights at Planet Labs.
show_downloads: false
google_analytics: G-RJ80K62TF0
theme: jekyll-theme-minimal
